print('==========================================')
print('         CÁLCULO DE MÉDIA ESCOLAR         ')
print('==========================================')
print('GitHub: tleitejr')
print('')
print('  Bem-vindo ao cálculo de média escolar   ')
print('')
print('OBS: O cálculo será de 4 notas para a média; \n Utilize "." \n Exemplo: 5.0')
print('')
media_minima = float(input('Digite a média mínima para um estudante passar de ano: '))
print('')
print('Ok, vamos lá!')
print('')
nota1 = float(input('Digite a 1ª nota: '))
nota2 = float(input('Agora a 2ª nota: '))
nota3 = float(input('A 3ª nota: '))
nota4 = float(input('E a 4ª para fechar: '))
print('')
print('Ok.')
print('')
media = (nota1 + nota2 + nota3 + nota4) // 4
if media >= media_minima:
    print('Parabéns, você passou!')
    print('Sua média: {}'.format(media))
    print('Média mínima: {}'.format(media_minima))
    print('========================================')
elif media < media_minima:
    print('Lamento, você foi reprovado...')
    print('Sua média: {}'.format(media))
    print('Média mínima: {}'.format(media_minima))
    print('========================================')
print('')
print('Obrigado por usar :)')
